### ISSUE TITLE
Link checker no longer works

### ISSUE THREAD

**Issue by r4v5** [felixbreton/felixbreton.github.io#1]
I'm a huge fan of your scihub link checker, but noticed it's stopped working since I last used it. It looks like a combination of a redesign that moved the raven image and a switch to HTTPS on the scihub side have made the checks against all URLs fail.

**Comment by felixbreton** [comment]
I replaced the URL of the raven image, thanks for opening the issue. Also, note that I have stopped maintaining my Github pages website, and this tool now lives (with better CSS) at https://felixbreton.com/scihub/ .
